### ISSUE TITLE
vector of the major axis of the fitting ellipsoid

### ISSUE THREAD

**Issue by zilinyan** [mdoube/BoneJ#59]
Hi @mdoube ,
Thanks for the codes. I tried the 3D particle analyzer on my randomly oriented ellipsoid particles (about 2000).  Their major axes are expected to distributed randomly in 3D space. I plot the unit vector of the major axis (vX, vY, vZ). It shows that most of the Vz values are assigned a positive value? What is the consideration for this if it is not a bug? thanks!
![image](https://user-images.githubusercontent.com/45580779/52756737-bfc8df00-3045-11e9-8949-0c9619f023b7.png)

**Comment by mdoube** [comment]
@zilinyan thanks for the report. This is not a bug. Bear in mind that orientation doesn't have a sign (unlike a vector, which does), because 0° = 180°, so your distribution is not too concerning. It is a bit weird that the unit vectors are clustered towards +Vz rather than being uniformly distributed, which is probably an artefact of the fitting maths. From this single projection it's a bit tricky to see whether the same phenomenon exists in Vx and Vy (which it might).

If you want to check whether the unit vectors make sense, display the output in the 3D viewer, showing the ellipsoid axes and principal axes. Also, [this forum post might be interesting for you](https://forum.image.sc/t/lacunae-orientation/21100).
